name: Daily Commit Automation

on:
  schedule:
    - cron: '05 4 * * *'  # Runs daily at 04:05 UTC
  workflow_dispatch:     # Also allows manual trigger from UI

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update with email 24f1002552@ds.study.iitm.ac.in
        run: |
          echo "Last updated on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "chore: daily update - $(date '+%Y-%m-%d %H:%M')"
          git push
